mass: 1.478

W_vertices: 
- [-1, -1, -1] 
- [-1, 1, -1] 
- [1, -1, -1] 
- [1, 1, -1] 
- [-1, -1, 1] 
- [-1, 1, 1] 
- [1, -1, 1] 
- [1, 1, 1]

state_keys: ['d_xq', 'd_yq', 'd_z', 'roll', 'rolld', 'pitch', 'pitchd', 'yawd', 'prev_uwx_b', 'prev_uwy_b']

inputs_keys: ['ux', 'uy', 'uz', 'uwz']

Q: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
R: [0.1, 0.1, 0.1, 0.1]
