/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_dynamics_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

static const casadi_real casadi_c0[144] = 
  {1., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  5.0000000000000010e-03, 1.0000000000000001e-01, 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 1.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 5.0000000000000010e-03,
  1.0000000000000001e-01, 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 1., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 5.0000000000000010e-03, 1.0000000000000001e-01,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 1.0000000000000001e-01, 1., -5.2500000000000000e+00, 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 5.0000000000000010e-03, 1.0000000000000001e-01, 0.};
static const casadi_real casadi_c1[96] = 
  {0., 0., 1.7000000000000002e+00, 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 3.3999999999999995e+00, 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1.7000000000000002e+00, 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 3.3999999999999995e+00, 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  1.7000000000000002e+00, 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 3.3999999999999995e+00, 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 2.6250000000000000e+00, 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 2.6250000000000000e+00};

/* drone_dynamics_dyn_disc_phi_fun:(i0[16],i1[4],i2[0])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+12, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, *w18=w+184, *w19=w+200, *w20=w+212, *w22=w+320;
  const casadi_real *cs, *ct, *wr01, *wr21;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w00, 12);
  /* #1: @1 = 
  [[1, 0.1, 0.005, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, -5.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 1, 0.1, 0.005, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 0.1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, -5.1, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 1, 0.1, 0.005, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 1, 0.1, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, -5.1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.1, 0.005], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.1], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -5.25, 0]] */
  wr01 = casadi_c0;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = input[0][15] */
  w17 = arg[0] ? arg[0][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:12] */
  for (rr=w19, cs=w18+0; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #20: @20 = mac(@1,@19,@0) */
  casadi_copy(w00, 12, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<12; ++j, ++rr) for (k=0, cs=wr01+j, ct=w19+i*12; k<12; ++k) *rr += cs[k*12]**ct++;
  /* #21: @21 = 
  [[0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [1.7, 3.4, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1.7, 3.4, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1.7, 3.4, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 2.625, 2.625]] */
  wr21 = casadi_c1;
  /* #22: @2 = input[1][0] */
  w02 = arg[1] ? arg[1][0] : 0;
  /* #23: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #24: @4 = input[1][2] */
  w04 = arg[1] ? arg[1][2] : 0;
  /* #25: @5 = input[1][3] */
  w05 = arg[1] ? arg[1][3] : 0;
  /* #26: @22 = vertcat(@14, @2, @15, @3, @16, @4, @17, @5) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w15;
  *rr++ = w03;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w17;
  *rr++ = w05;
  /* #27: @0 = mac(@21,@22,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<12; ++j, ++rr) for (k=0, cs=wr21+j, ct=w22+i*8; k<8; ++k) *rr += cs[k*12]**ct++;
  /* #28: @20 = (@20+@0) */
  for (i=0, rr=w20, cs=w00; i<12; ++i) (*rr++) += (*cs++);
  /* #29: output[0][0] = @20 */
  casadi_copy(w20, 12, res[0]);
  /* #30: @6 = 0.333333 */
  w06 = 3.3333333333333337e-01;
  /* #31: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #32: @7 = 0.666667 */
  w07 = 6.6666666666666663e-01;
  /* #33: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #34: @14 = (@14+@2) */
  w14 += w02;
  /* #35: output[0][1] = @14 */
  if (res[0]) res[0][12] = w14;
  /* #36: @15 = (@6*@15) */
  w15  = (w06*w15);
  /* #37: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #38: @15 = (@15+@3) */
  w15 += w03;
  /* #39: output[0][2] = @15 */
  if (res[0]) res[0][13] = w15;
  /* #40: @6 = (@6*@16) */
  w06 *= w16;
  /* #41: @7 = (@7*@4) */
  w07 *= w04;
  /* #42: @6 = (@6+@7) */
  w06 += w07;
  /* #43: output[0][3] = @6 */
  if (res[0]) res[0][14] = w06;
  /* #44: @6 = 0.5 */
  w06 = 5.0000000000000000e-01;
  /* #45: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #46: @6 = (@6*@5) */
  w06 *= w05;
  /* #47: @17 = (@17+@6) */
  w17 += w06;
  /* #48: output[0][4] = @17 */
  if (res[0]) res[0][15] = w17;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_dynamics_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_dynamics_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_dynamics_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_dynamics_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_dynamics_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_dynamics_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_dynamics_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 328;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 328*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
