/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_dynamics_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[16] = 
  {12, 1, 0, 12, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[5] = {8, 1, 0, 1, 1};
static const casadi_int casadi_s2[107] = 
  {12, 8, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s3[5] = {8, 1, 0, 1, 3};
static const casadi_int casadi_s4[13] = 
  {1, 21, 41, 61, 81, 101, 121, 141,
  161, 181, 201, 221, 242};
static const casadi_int casadi_s5[5] = {8, 1, 0, 1, 5};
static const casadi_int casadi_s6[13] = 
  {2, 22, 42, 62, 82, 102, 122, 142,
  162, 182, 202, 222, 244};
static const casadi_int casadi_s7[5] = {8, 1, 0, 1, 7};
static const casadi_int casadi_s8[13] = 
  {3, 23, 43, 63, 83, 103, 123, 143,
  163, 183, 203, 223, 246};
static const casadi_int casadi_s9[5] = {12, 1, 0, 1, 0};
static const casadi_int casadi_s10[159] = 
  {12, 12, 0, 12, 24, 36, 48, 60,
  72, 84, 96, 108, 120, 132, 144, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s11[5] = {12, 1, 0, 1, 1};
static const casadi_int casadi_s12[5] = {12, 1, 0, 1, 2};
static const casadi_int casadi_s13[5] = {12, 1, 0, 1, 3};
static const casadi_int casadi_s14[5] = {12, 1, 0, 1, 4};
static const casadi_int casadi_s15[5] = {12, 1, 0, 1, 5};
static const casadi_int casadi_s16[5] = {12, 1, 0, 1, 6};
static const casadi_int casadi_s17[5] = {12, 1, 0, 1, 7};
static const casadi_int casadi_s18[5] = {12, 1, 0, 1, 8};
static const casadi_int casadi_s19[5] = {12, 1, 0, 1, 9};
static const casadi_int casadi_s20[5] = {12, 1, 0, 1, 10};
static const casadi_int casadi_s21[5] = {12, 1, 0, 1, 11};
static const casadi_int casadi_s22[5] = {8, 1, 0, 1, 0};
static const casadi_int casadi_s23[13] = 
  {16, 36, 56, 76, 96, 116, 136, 156,
  176, 196, 216, 236, 241};
static const casadi_int casadi_s24[5] = {8, 1, 0, 1, 2};
static const casadi_int casadi_s25[13] = 
  {17, 37, 57, 77, 97, 117, 137, 157,
  177, 197, 217, 237, 243};
static const casadi_int casadi_s26[5] = {8, 1, 0, 1, 4};
static const casadi_int casadi_s27[13] = 
  {18, 38, 58, 78, 98, 118, 138, 158,
  178, 198, 218, 238, 245};
static const casadi_int casadi_s28[5] = {8, 1, 0, 1, 6};
static const casadi_int casadi_s29[13] = 
  {19, 39, 59, 79, 99, 119, 139, 159,
  179, 199, 219, 239, 247};
static const casadi_int casadi_s30[3] = {16, 1, 1};
static const casadi_int casadi_s31[3] = {4, 1, 1};
static const casadi_int casadi_s32[3] = {0, 1, 1};
static const casadi_int casadi_s33[267] = 
  {20, 16, 0, 20, 40, 60, 80, 100,
  120, 140, 160, 180, 200, 220, 240, 242,
  244, 246, 248, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 0, 16, 1, 17, 2,
  18, 3, 19};
static const casadi_int casadi_s34[23] = 
  {20, 20, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[144] = 
  {1., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  5.0000000000000010e-03, 1.0000000000000001e-01, 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 1.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 5.0000000000000010e-03,
  1.0000000000000001e-01, 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 1., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 1.0000000000000001e-01, 1., -5.0999999999999996e+00, 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 5.0000000000000010e-03, 1.0000000000000001e-01,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 1.0000000000000001e-01, 1., -5.2500000000000000e+00, 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 5.0000000000000010e-03, 1.0000000000000001e-01, 0.};
static const casadi_real casadi_c1[96] = 
  {0., 0., 1.7000000000000002e+00, 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 3.3999999999999995e+00, 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 1.7000000000000002e+00, 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 3.3999999999999995e+00, 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  1.7000000000000002e+00, 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 3.3999999999999995e+00, 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 2.6250000000000000e+00, 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 2.6250000000000000e+00};

/* drone_dynamics_dyn_disc_phi_fun_jac_hess:(i0[16],i1[4],i2[16],i3[0])->(o0[16],o1[20x16,248nz],o2[20x20,0nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+12, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, *w18=w+184, *w19=w+200, *w20=w+212, *w22=w+320, *w23=w+328, *w25=w+576;
  casadi_real *w26=w+589;
  const casadi_int *cii;
  const casadi_real *cs, *ct, *wr01, *wr21;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w00, 12);
  /* #1: @1 = 
  [[1, 0.1, 0.005, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, -5.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 1, 0.1, 0.005, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1, 0.1, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, -5.1, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 1, 0.1, 0.005, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 1, 0.1, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, -5.1, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.1, 0.005], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.1], 
   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -5.25, 0]] */
  wr01 = casadi_c0;
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #9: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #10: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #11: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #12: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #13: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #14: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #15: @15 = input[0][13] */
  w15 = arg[0] ? arg[0][13] : 0;
  /* #16: @16 = input[0][14] */
  w16 = arg[0] ? arg[0][14] : 0;
  /* #17: @17 = input[0][15] */
  w17 = arg[0] ? arg[0][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:12] */
  for (rr=w19, cs=w18+0; cs!=w18+12; cs+=1) *rr++ = *cs;
  /* #20: @20 = mac(@1,@19,@0) */
  casadi_copy(w00, 12, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<12; ++j, ++rr) for (k=0, cs=wr01+j, ct=w19+i*12; k<12; ++k) *rr += cs[k*12]**ct++;
  /* #21: @21 = 
  [[0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [1.7, 3.4, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 1.7, 3.4, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 1.7, 3.4, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 0, 0], 
   [0, 0, 0, 0, 0, 0, 2.625, 2.625]] */
  wr21 = casadi_c1;
  /* #22: @2 = input[1][0] */
  w02 = arg[1] ? arg[1][0] : 0;
  /* #23: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #24: @4 = input[1][2] */
  w04 = arg[1] ? arg[1][2] : 0;
  /* #25: @5 = input[1][3] */
  w05 = arg[1] ? arg[1][3] : 0;
  /* #26: @22 = vertcat(@14, @2, @15, @3, @16, @4, @17, @5) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w02;
  *rr++ = w15;
  *rr++ = w03;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w17;
  *rr++ = w05;
  /* #27: @19 = mac(@21,@22,@0) */
  casadi_copy(w00, 12, w19);
  for (i=0, rr=w19; i<1; ++i) for (j=0; j<12; ++j, ++rr) for (k=0, cs=wr21+j, ct=w22+i*8; k<8; ++k) *rr += cs[k*12]**ct++;
  /* #28: @20 = (@20+@19) */
  for (i=0, rr=w20, cs=w19; i<12; ++i) (*rr++) += (*cs++);
  /* #29: output[0][0] = @20 */
  casadi_copy(w20, 12, res[0]);
  /* #30: @6 = 0.333333 */
  w06 = 3.3333333333333337e-01;
  /* #31: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #32: @7 = 0.666667 */
  w07 = 6.6666666666666663e-01;
  /* #33: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #34: @14 = (@14+@2) */
  w14 += w02;
  /* #35: output[0][1] = @14 */
  if (res[0]) res[0][12] = w14;
  /* #36: @15 = (@6*@15) */
  w15  = (w06*w15);
  /* #37: @3 = (@7*@3) */
  w03  = (w07*w03);
  /* #38: @15 = (@15+@3) */
  w15 += w03;
  /* #39: output[0][2] = @15 */
  if (res[0]) res[0][13] = w15;
  /* #40: @16 = (@6*@16) */
  w16  = (w06*w16);
  /* #41: @4 = (@7*@4) */
  w04  = (w07*w04);
  /* #42: @16 = (@16+@4) */
  w16 += w04;
  /* #43: output[0][3] = @16 */
  if (res[0]) res[0][14] = w16;
  /* #44: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #45: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #46: @5 = (@16*@5) */
  w05  = (w16*w05);
  /* #47: @17 = (@17+@5) */
  w17 += w05;
  /* #48: output[0][4] = @17 */
  if (res[0]) res[0][15] = w17;
  /* #49: @23 = zeros(20x16,248nz) */
  casadi_clear(w23, 248);
  /* #50: @24 = 00 */
  /* #51: @17 = ones(20x1,1nz) */
  w17 = 1.;
  /* #52: {@5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@17) */
  w05 = w17;
  /* #53: @17 = vertcat(@24, @5, @24, @24, @24, @24, @24, @24) */
  rr=(&w17);
  *rr++ = w05;
  /* #54: @20 = mac(@21,@17,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w17), casadi_s1, w20, casadi_s0, w, 0);
  /* #55: @5 = (@7*@5) */
  w05  = (w07*w05);
  /* #56: @25 = vertcat(@20, @5, @24, @24, @24) */
  rr=w25;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w05;
  /* #57: @26 = @25[:13] */
  for (rr=w26, cs=w25+0; cs!=w25+13; cs+=1) *rr++ = *cs;
  /* #58: (@23[:260:20] = @26) */
  for (rr=w23+0, cs=w26; rr!=w23+260; rr+=20) *rr = *cs++;
  /* #59: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #60: {NULL, @17, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w17 = w05;
  /* #61: @5 = vertcat(@24, @24, @24, @17, @24, @24, @24, @24) */
  rr=(&w05);
  *rr++ = w17;
  /* #62: @20 = mac(@21,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w05), casadi_s3, w20, casadi_s0, w, 0);
  /* #63: @17 = (@7*@17) */
  w17  = (w07*w17);
  /* #64: @26 = vertcat(@20, @24, @17, @24, @24) */
  rr=w26;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w17;
  /* #65: @25 = @26[:13] */
  for (rr=w25, cs=w26+0; cs!=w26+13; cs+=1) *rr++ = *cs;
  /* #66: (@23[1, 21, 41, 61, 81, 101, 121, 141, 161, 181, 201, 221, 242] = @25) */
  for (cii=casadi_s4, rr=w23, cs=w25; cii!=casadi_s4+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #67: @17 = ones(20x1,1nz) */
  w17 = 1.;
  /* #68: {NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@17) */
  w05 = w17;
  /* #69: @17 = vertcat(@24, @24, @24, @24, @24, @5, @24, @24) */
  rr=(&w17);
  *rr++ = w05;
  /* #70: @20 = mac(@21,@17,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w17), casadi_s5, w20, casadi_s0, w, 0);
  /* #71: @7 = (@7*@5) */
  w07 *= w05;
  /* #72: @25 = vertcat(@20, @24, @24, @7, @24) */
  rr=w25;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w07;
  /* #73: @26 = @25[:13] */
  for (rr=w26, cs=w25+0; cs!=w25+13; cs+=1) *rr++ = *cs;
  /* #74: (@23[2, 22, 42, 62, 82, 102, 122, 142, 162, 182, 202, 222, 244] = @26) */
  for (cii=casadi_s6, rr=w23, cs=w26; cii!=casadi_s6+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #75: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #76: {NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #77: @7 = vertcat(@24, @24, @24, @24, @24, @24, @24, @5) */
  rr=(&w07);
  *rr++ = w05;
  /* #78: @20 = mac(@21,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w07), casadi_s7, w20, casadi_s0, w, 0);
  /* #79: @5 = (@16*@5) */
  w05  = (w16*w05);
  /* #80: @26 = vertcat(@20, @24, @24, @24, @5) */
  rr=w26;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w05;
  /* #81: @25 = @26[:13] */
  for (rr=w25, cs=w26+0; cs!=w26+13; cs+=1) *rr++ = *cs;
  /* #82: (@23[3, 23, 43, 63, 83, 103, 123, 143, 163, 183, 203, 223, 246] = @25) */
  for (cii=casadi_s8, rr=w23, cs=w25; cii!=casadi_s8+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #83: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #84: {NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #85: @7 = sparsity_cast(@7) */
  /* #86: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s9, w20, casadi_s0, w, 0);
  /* #87: (@23[4:244:20] = @20) */
  for (rr=w23+4, cs=w20; rr!=w23+244; rr+=20) *rr = *cs++;
  /* #88: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #89: {NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #90: @5 = sparsity_cast(@5) */
  /* #91: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s11, w20, casadi_s0, w, 0);
  /* #92: (@23[5:245:20] = @20) */
  for (rr=w23+5, cs=w20; rr!=w23+245; rr+=20) *rr = *cs++;
  /* #93: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #94: {NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #95: @7 = sparsity_cast(@7) */
  /* #96: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s12, w20, casadi_s0, w, 0);
  /* #97: (@23[6:246:20] = @20) */
  for (rr=w23+6, cs=w20; rr!=w23+246; rr+=20) *rr = *cs++;
  /* #98: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #99: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #100: @5 = sparsity_cast(@5) */
  /* #101: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s13, w20, casadi_s0, w, 0);
  /* #102: (@23[7:247:20] = @20) */
  for (rr=w23+7, cs=w20; rr!=w23+247; rr+=20) *rr = *cs++;
  /* #103: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #104: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #105: @7 = sparsity_cast(@7) */
  /* #106: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s14, w20, casadi_s0, w, 0);
  /* #107: (@23[8:248:20] = @20) */
  for (rr=w23+8, cs=w20; rr!=w23+248; rr+=20) *rr = *cs++;
  /* #108: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #109: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #110: @5 = sparsity_cast(@5) */
  /* #111: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s15, w20, casadi_s0, w, 0);
  /* #112: (@23[9:249:20] = @20) */
  for (rr=w23+9, cs=w20; rr!=w23+249; rr+=20) *rr = *cs++;
  /* #113: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #114: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #115: @7 = sparsity_cast(@7) */
  /* #116: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s16, w20, casadi_s0, w, 0);
  /* #117: (@23[10:250:20] = @20) */
  for (rr=w23+10, cs=w20; rr!=w23+250; rr+=20) *rr = *cs++;
  /* #118: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #119: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #120: @5 = sparsity_cast(@5) */
  /* #121: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s17, w20, casadi_s0, w, 0);
  /* #122: (@23[11:251:20] = @20) */
  for (rr=w23+11, cs=w20; rr!=w23+251; rr+=20) *rr = *cs++;
  /* #123: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #124: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #125: @7 = sparsity_cast(@7) */
  /* #126: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s18, w20, casadi_s0, w, 0);
  /* #127: (@23[12:252:20] = @20) */
  for (rr=w23+12, cs=w20; rr!=w23+252; rr+=20) *rr = *cs++;
  /* #128: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #129: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #130: @5 = sparsity_cast(@5) */
  /* #131: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s19, w20, casadi_s0, w, 0);
  /* #132: (@23[13:253:20] = @20) */
  for (rr=w23+13, cs=w20; rr!=w23+253; rr+=20) *rr = *cs++;
  /* #133: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #134: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #135: @7 = sparsity_cast(@7) */
  /* #136: @20 = mac(@1,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w07), casadi_s20, w20, casadi_s0, w, 0);
  /* #137: (@23[14:254:20] = @20) */
  for (rr=w23+14, cs=w20; rr!=w23+254; rr+=20) *rr = *cs++;
  /* #138: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #139: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #140: @5 = sparsity_cast(@5) */
  /* #141: @20 = mac(@1,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr01, casadi_s10, (&w05), casadi_s21, w20, casadi_s0, w, 0);
  /* #142: (@23[15:255:20] = @20) */
  for (rr=w23+15, cs=w20; rr!=w23+255; rr+=20) *rr = *cs++;
  /* #143: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #144: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #145: @5 = vertcat(@7, @24, @24, @24, @24, @24, @24, @24) */
  rr=(&w05);
  *rr++ = w07;
  /* #146: @20 = mac(@21,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w05), casadi_s22, w20, casadi_s0, w, 0);
  /* #147: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #148: @25 = vertcat(@20, @7, @24, @24, @24) */
  rr=w25;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w07;
  /* #149: @26 = @25[:13] */
  for (rr=w26, cs=w25+0; cs!=w25+13; cs+=1) *rr++ = *cs;
  /* #150: (@23[16, 36, 56, 76, 96, 116, 136, 156, 176, 196, 216, 236, 241] = @26) */
  for (cii=casadi_s23, rr=w23, cs=w26; cii!=casadi_s23+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #151: @7 = ones(20x1,1nz) */
  w07 = 1.;
  /* #152: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL} = vertsplit(@7) */
  w05 = w07;
  /* #153: @7 = vertcat(@24, @24, @5, @24, @24, @24, @24, @24) */
  rr=(&w07);
  *rr++ = w05;
  /* #154: @20 = mac(@21,@7,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w07), casadi_s24, w20, casadi_s0, w, 0);
  /* #155: @5 = (@6*@5) */
  w05  = (w06*w05);
  /* #156: @26 = vertcat(@20, @24, @5, @24, @24) */
  rr=w26;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w05;
  /* #157: @25 = @26[:13] */
  for (rr=w25, cs=w26+0; cs!=w26+13; cs+=1) *rr++ = *cs;
  /* #158: (@23[17, 37, 57, 77, 97, 117, 137, 157, 177, 197, 217, 237, 243] = @25) */
  for (cii=casadi_s25, rr=w23, cs=w25; cii!=casadi_s25+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #159: @5 = ones(20x1,1nz) */
  w05 = 1.;
  /* #160: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7, NULL} = vertsplit(@5) */
  w07 = w05;
  /* #161: @5 = vertcat(@24, @24, @24, @24, @7, @24, @24, @24) */
  rr=(&w05);
  *rr++ = w07;
  /* #162: @20 = mac(@21,@5,@0) */
  casadi_copy(w00, 12, w20);
  casadi_mtimes(wr21, casadi_s2, (&w05), casadi_s26, w20, casadi_s0, w, 0);
  /* #163: @6 = (@6*@7) */
  w06 *= w07;
  /* #164: @25 = vertcat(@20, @24, @24, @6, @24) */
  rr=w25;
  for (i=0, cs=w20; i<12; ++i) *rr++ = *cs++;
  *rr++ = w06;
  /* #165: @26 = @25[:13] */
  for (rr=w26, cs=w25+0; cs!=w25+13; cs+=1) *rr++ = *cs;
  /* #166: (@23[18, 38, 58, 78, 98, 118, 138, 158, 178, 198, 218, 238, 245] = @26) */
  for (cii=casadi_s27, rr=w23, cs=w26; cii!=casadi_s27+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #167: @6 = ones(20x1,1nz) */
  w06 = 1.;
  /* #168: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @7} = vertsplit(@6) */
  w07 = w06;
  /* #169: @6 = vertcat(@24, @24, @24, @24, @24, @24, @7, @24) */
  rr=(&w06);
  *rr++ = w07;
  /* #170: @0 = mac(@21,@6,@0) */
  casadi_mtimes(wr21, casadi_s2, (&w06), casadi_s28, w00, casadi_s0, w, 0);
  /* #171: @16 = (@16*@7) */
  w16 *= w07;
  /* #172: @26 = vertcat(@0, @24, @24, @24, @16) */
  rr=w26;
  for (i=0, cs=w00; i<12; ++i) *rr++ = *cs++;
  *rr++ = w16;
  /* #173: @25 = @26[:13] */
  for (rr=w25, cs=w26+0; cs!=w26+13; cs+=1) *rr++ = *cs;
  /* #174: (@23[19, 39, 59, 79, 99, 119, 139, 159, 179, 199, 219, 239, 247] = @25) */
  for (cii=casadi_s29, rr=w23, cs=w25; cii!=casadi_s29+13; ++cii, ++cs) rr[*cii] = *cs;
  /* #175: output[1][0] = @23 */
  casadi_copy(w23, 248, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_dynamics_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_dynamics_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_dynamics_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_dynamics_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_dynamics_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_dynamics_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_dynamics_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s30;
    case 1: return casadi_s31;
    case 2: return casadi_s30;
    case 3: return casadi_s32;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_dynamics_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s30;
    case 1: return casadi_s33;
    case 2: return casadi_s34;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 602;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_dynamics_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 23*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 602*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
